---
collections:
  - name: google.cloud
    version: 1.0.2
  - name: amazon.aws
    version: 1.5.0
  - name: community.aws
    version: 1.5.0
  - name: servicenow.itsm
    version: 1.1.0
  - name: community.general
    version: 3.4.0
  - name: michaelford85.reports
    version: 1.1.6
  
