---
collections:
  - name: google.cloud
    version: 1.0.2
  - name: amazon.aws
    version: 1.5.0
  - name: community.aws
    version: 1.5.0
  - name: servicenow.itsm
    version: 1.1.0
  - name: community.general
    version: 3.4.0
  - name: michaelford85.reports
    version: 1.1.6
  - name: ansible.tower
    version: 3.8.3
  - name: community.crypto
    version: 1.9.5
  - name: containers.podman
    version: 1.8.1
  
