- name: Copy Ansible Logo
  ansible.builtin.copy:
    src: webpage_logo.png
    dest: /var/www/html/
  become: yes

- name: Copy CSS
  ansible.builtin.copy:
    src: css
    dest: /var/www/html/
  become: yes

- name: create HTML report
  ansible.builtin.template:
    src: report.j2
    dest: /var/www/html/index.html
  become: yes
  notify: restart_apache

- name: update directory permissions
  ansible.builtin.file:
    path: /var/www/html
    state: directory
    recurse: yes
    mode: '0755'
  become: yes
  notify: restart_apache
