---
- name: Ensure Instance Services
  hosts: all
  gather_facts: no
  vars_files:
    - ./vars/default-vars.yml
    - ./credentials/redhat-activation-key.yml

  tasks:

  - name: Ensure GCP Instance Services
    block:

      - name: Set up Linux Instances on GCP
        include_role:
          name: gcp-deploy
          tasks_from: ensure-services

    when: cloud_provider == "gcp"

  - name: Ensure AWS Instance Services
    block:

      - name: Set up Linux Instances on AWS
        include_role:
          name: aws-deploy
          tasks_from: ensure-services

    when: cloud_provider == "aws"
