---
- name: Provision GCP Resources
  hosts: localhost
  gather_facts: no
  vars_files:
    - ./vars/default-vars.yml
    - ./credentials/snow_creds.yml

  tasks:

    - name: create a disk
      gcp_compute_disk:
        name: 'disk-instance'
        size_gb: 50
        source_image: 'projects/ubuntu-os-cloud/global/images/family/ubuntu-1604-lts'
        # zone: "{{ zone }}"
        # project: "{{ gcp_project }}"
        # auth_kind: "{{ gcp_cred_kind }}"
        # service_account_file: "{{ gcp_cred_file }}"
        scopes:
          - https://www.googleapis.com/auth/compute
        state: present
