---
- name: Ensure Standard RHEL8 Configuration
  hosts: all
  gather_facts: yes
  vars_files:
    - ./credentials/redhat-activation-key.yml

  tasks:

    - name: Ensure Standard Linux Configuration on GCP
      block:

        - name: Ensure Standard Linux Configuration GCP
          ansible.builtin.include_role:
            name: gcp-deploy
            tasks_from: provision-linux

      when: cloud_provider == "gcp"

    - name: Ensure Standard Linux Configuration on AWS
      block:

        - name: Ensure Standard Linux Configuration on AWS
          ansible.builtin.include_role:
            name: aws-deploy
            tasks_from: provision-linux

      when: cloud_provider == "aws"
