---
- name: Ensure vault is running
  hosts: all
  gather_facts: no
  vars_files:
    - ./vars/default-vars.yml
    - ./credentials/vault_creds.yml
    - ./credentials/tower_creds.yml

  tasks:

    - name: Set up secrets engine on GCP
      block:

        - name: Set up secrets engine on GCP
          include_role:
            name: gcp-deploy
            tasks_from: install-vault-podman

      when: cloud_provider == "gcp"

    - name: Set up secrets engine on AWS
      block:

        - name: Set up secrets engine on  AWS
          include_role:
            name: aws-deploy
            tasks_from: install-vault-podman

      when: cloud_provider == "aws"
