- name: ServiceNow Update Change Request
  hosts: localhost
  gather_facts: no
  vars_files:
    - ./credentials/snow_creds.yml
    - ./vars/default-vars.yml

  tasks:

    - name: Include Change Request artifact
      ansible.builtin.include_vars: "{{ working_dir }}/snow-change-request.yml"
      when: from_snow|bool

    - name: Update Change Request
      servicenow.itsm.change_request:
        instance:
            host: "https://{{ SNOW_INSTANCE }}.service-now.com"
            username: "{{ SNOW_USERNAME }}"
            password: "{{ SNOW_PASSWORD }}"
        sys_id: "{{ snow_cr_sys_id }}"
        close_code: "{{ close_code }}"
        close_notes: "{{ close_notes }}"
        state: "{{ close_state }}"
      register: change_request_status

    # - name: Show Change Request details
    #   debug:
    #     var: change_request_status.record.state

    - block:
      - name: Remove Change Request Variable file
        ansible.builtin.file:
          path: "{{ working_dir }}/snow-change-request.yml"
          state: absent
        when: ((change_request_status.record.state == "closed") or
              (change_request_status.record.state == "canceled"))
      when: from_snow|bool

    #state
    # -5 is just created
    # -4 means approval has been requested
    # -3 means partial approval
    # -2 means it has been approved
    # -1 means it is in the implement stage
    # 0 means it is in the review state
    # 3 means CR closed successfully (perhaps with issues)
    # 4 means cancelled
    #https://docs.servicenow.com/bundle/orlando-it-service-management/page/product/change-management/task/state-model-activate-tasks.html

    #approval
    # - not requested
    # - requested
    # - approved

    #close_code
    # - successful
    # - successful with issues
    # - unsuccessful

    #closed_notes
