- name: ServiceNow Create New Change Request
  hosts: localhost
  gather_facts: no
  vars_files:
    - ./credentials/snow_creds.yml
    - ./credentials/gmail_creds.yml
    - ./vars/default-vars.yml
  collections:
    - servicenow.servicenow

  tasks:
    # - name: Create ServiceNow Change Request (OLD)
    #   snow_record:
    #     username: "{{ SNOW_USERNAME }}"
    #     password: "{{ SNOW_PASSWORD }}"
    #     instance: "{{ SNOW_INSTANCE }}"
    #     table: change_request
    #     state: present
    #     data:
    #       short_description: "Deploy Cloud RHEL Instances"
    #       severity: 3
    #       priority: 2
    #       assignment_group: "CAB Approval"
    #       approval: "requested"
    #       state: -4
    #   register: new_change_request
    #   when: from_snow|bool

    - name: Create ServiceNow Change Request (NEW)
      servicenow.itsm.change_request:
        instance:
          host: "https://{{ SN_INSTANCE }}.service-now.com"
          username: "{{ SN_USERNAME }}"
          password: "{{ SN_PASSWORD }}"
        type: normal
        priority: high
        risk: moderate
        other:
          approval: requested
        state: assess
        assignment_group: "CAB Approval"
        short_description: "Deploy Cloud RHEL Instances"
        description: "Deploy Cloud RHEL Instances"
      register: new_change_request
      when: from_snow|bool

    # - name: Show Change Request details
    #   debug:
    #     var: new_change_request
    #   when: from_snow|bool

    - name: Store Change Request number as artifact for later in the workflow
      ansible.builtin.template:
        src: ./templates/snow-change-request.j2
        dest: "{{ working_dir }}/snow-change-request.yml"
      run_once: yes
      delegate_to: localhost
      when: from_snow|bool

    - name: Print out Change Request number
      ansible.builtin.debug:
        msg: "The newly created Change Request is {{ new_change_request.record.number }}. Awaiting Approval."
      when: from_snow|bool

    #https://www.infinitypp.com/ansible/email-notifications-with-examples/
    - name: Sending an email requesting approval
      ansible.builtin.mail:
        host: smtp.gmail.com
        port: 587
        username: "{{ gmail_username }}"
        password: "{{ gmail_password }}"
        to:
        - "Michael Ford <{{ approver_email }}>"
        - "{{secondary_approver}}"
        #- "{{tertiary_approver}}"
        subject: "Approval request for ServiceNow Change Request {{ new_change_request.record.number }}"
        body: "You have a new CR Approval request. Please click on this URL to approve: https://{{ SNOW_INSTANCE }}.service-now.com/nav_to.do?uri=change_request.do?sysparm_query=number={{ new_change_request.record.number }}"
      delegate_to: localhost
      when: from_snow|bool

    - name: Wait for Change Request approval
      snow_record_find:
        username: "{{ SNOW_USERNAME }}"
        password: "{{ SNOW_PASSWORD }}"
        instance: "{{ SNOW_INSTANCE }}"
        table: change_request
        query:
          AND:
            equals:
              number: "{{ new_change_request.record.number }}"
      register: change_request_status
      when: from_snow|bool
      until: change_request_status.record[0].state == "-2"
      retries: 50
      delay: 10

    - ansible.builtin.debug:
        msg: "Change Request {{ new_change_request.record.number }} has been approved!"
      when: from_snow|bool

    - name: Move Change Request to Review stage
      snow_record:
        username: "{{ SNOW_USERNAME }}"
        password: "{{ SNOW_PASSWORD }}"
        instance: "{{ SNOW_INSTANCE }}"
        table: change_request
        number: "{{ new_change_request.record.number }}"
        state: present
        data:
          state: "{{ item }}"
      when: from_snow|bool
      loop:
        - "-1"
        - "0"



    #state
    # -5 is just created
    # -4 means approval has been requested
    # -3 means partial approval
    # -2 means it has been approved
    # -1 means it is in the implement stage
    # 0 means it is in the review state
    # 3 means CR closed successfully (perhaps with issues)

    #approval
    # - not requested
    # - requested
    # - approved

    #close_code
    # - successful
    # - successful with issues
    # - unsuccessful

    #closed_notes
