---
- name: Teardown AWS infrastructure via Terraform
  hosts: localhost
  gather_facts: no

  tasks:

    - name: Teardown GCP infrastructure via Terraform
      block:

        - name: Ensure GCP Terraform Directory Exists
          stat:
            path: /tmp/gcp_deploy
          register: gcp_deploy_directory

        - name: Teardown GCP infrastructure via Terraform
          terraform:
            project_path: /tmp/gcp_deploy
            variables:
              gcp_key: '{{ lookup("env", "GCE_CREDENTIALS_FILE_PATH") }}'
            state: absent
          register: terraform_output
          when: gcp_deploy_directory.stat.exists and gcp_deploy_directory.stat.isdir

        - name: Debug Terraform output
          debug:
            var: terraform_output
          tags:
            - debug

      when: cloud_provider == "gcp"

    - name: Teardown AWS infrastructure via Terraform
      block:

        - name: Ensure AWS Terraform Directory Exists
          stat:
            path: /tmp/aws_deploy
          register: aws_deploy_directory

        - name: Teardown AWS infrastructure via Terraform
          terraform:
            project_path: /tmp/aws_deploy
            state: absent
          register: terraform_output
          when: aws_deploy_directory.exists

        - name: Debug Terraform output
          debug:
            var: terraform_output
          tags:
            - debug

      when: cloud_provider == "aws"
