---
- name: "Create GCP VPC {{ gcp_prefix }}-vpc"
  google.cloud.gcp_compute_network:
    name: "{{ gcp_prefix }}-vpc"
    auto_create_subnetworks: 'false'
    state: present
  register: gcp_vpc

# - debug:
#     var: gcp_vpc


- name: "Create GCP Firewall for {{ gcp_prefix }}-vpc"
  google.cloud.gcp_compute_firewall:
    name: "{{ gcp_prefix }}-firewall"
    network: "{{ gcp_vpc }}"
    allowed:
    - ip_protocol: icmp
    - ip_protocol: tcp
      ports:
      - '22'
      - '80'
      - '443'
      - '8200'
      - '3306'
    target_tags:
    - appdeployment
    - "{{ application }}"
    state: present
  register: gcp_firewall


- name: "Create GCP Subnet for {{ gcp_prefix }}-vpc"
  google.cloud.gcp_compute_subnetwork:
    name: "{{ gcp_prefix }}-subnet"
    region: "{{ gcp_region }}"
    network: "{{ gcp_vpc }}"
    ip_cidr_range: "{{ gcp_vpc_subnet }}"
    state: present
  register: gcp_subnet
