---
- name: ensure firewall service is running
  service:
    name: '{{ item }}'
    state: started
    enabled: yes
  become: yes
  with_items:
    - firewalld # Add more services to this list as required
  when: tags.group == "rhel"
